# Education
- institution: King's College London
  degree: MSc, Advanced Software Engineering
  location: London, UK
  startDate: 2025-09
  endDate: 2026-09
  activities: Electronics Society Â· STEM Outreach Student Ambassador
  skills:
    - Web3
    - C
    - x86 Assembly
    - Multi-agent Systems
    - Software Testing
    - Software Measurement
    - Arduino
    - Human Computer Interaction
    - Japanese

- institution: Edinburgh Napier University
  degree: BSc (Hons), Cyber Security
  location: Edinburgh, UK
  startDate: 2021-09
  endDate: 2024-09
  grade: First-Class Honours
  skills:
    - GitHub
    - JavaScript
    - Arduino
    - Machine Learning
    - React.js
    - Node.js
    - Full-Stack Development
    - Tailwind CSS
    - Java
    - Software Engineering
    - Database Design
    - Next.js
    - C
    - Front-End Development
    - Terraform
    - Cloud Platforms
    - Web Design
    - Vercel
    - Information Security
    - Computer Science
    - Cyber Security
    - C++
    - Python
    - Google Cloud Platform (GCP)
    - WordPress
    - TypeScript
    - Machine Vision
