# Work Experience
- company: UK Civil Service
  position: Full-Stack Software Engineer
  location: United Kingdom (On-site)
  startDate: 2021-10
  endDate: present
  description: |
    Full-stack engineer delivering robust, scalable solutions for critical government operations. I lead end-to-end delivery across research, design, implementation, and maintenance, modernising legacy systems and streamlining deployment through DevOps and Infrastructure as Code.

- company: ThinkHuman
  position: Founder
  location: United Kingdom (Remote)
  startDate: 2025-12
  endDate: present
  description: |
   A software development agency that builds both in-house and client projects. We specialise in building web applications and mobile apps using modern technologies and best practices.