# Volunteering
- organization: STEM Ambassadors
  position: STEM Ambassador
  startDate: 2024-05
  endDate: present
  description: |
    Bringing STEM subjects to life for over 3 million young people across the UK. I work closely with local schools to inspire students and support teachers by explaining current industry and research applications of STEM.

- organization: CyberFirst South West
  position: CyberFirst Ambassador
  startDate: 2025-07
  endDate: present
  description: |
    Using my STEM expertise to inspire the next generation of cybersecurity professionals. I help open doors to opportunities in cyber careers and support young people as part of a dedicated cohort.

- organization: King's College London
  position: STEM Outreach Student Ambassador
  startDate: 2025-10
  endDate: present
  description: |
    Supporting STEM outreach initiatives at King's College London to engage and inspire young people in science, technology, engineering, and mathematics.

- organization: Cloud Imperium Games
  position: Citizencon 2954 BTS Volunteer
  startDate: 2024-09
  endDate: 2024-09
  description: |
    Worked behind the scenes with Cloud Imperium Games staff to bring CitizenCon 2954 to life, a convention with over 3000 attendees.

- organization: Uptree
  position: Guest Speaker
  startDate: 2024-03
  endDate: 2024-03
  description: |
    Invited to speak at FuturesUP!! event, sharing my journey in STEM with talented students and encouraging them to explore diverse educational paths including apprenticeships.

- organization: The Barn Owl Centre Ltd
  position: Fundraising and Conservation Volunteer
  startDate: 2019-08
  endDate: 2019-08
  description: |
    Raised thousands of pounds to support conservation efforts. Helped construct new bridges and undertook landscape management tasks at The Barn Owl Centre in Gloucester.
